# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Load weather_data.csv as dataframe
weather_data_df = pd.read_csv('../output_data/weather_data.csv')
weather_data_df

,City,Longitude,Latitude,Date,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Max Temperature (F)
0,pangnirtung,-65.7125,66.1451,1620956631,24.71,97,98,1.21,24.71
1,pangody,74.4859,65.8500,1620956632,31.08,97,100,15.01,31.08
2,ushuaia,-68.3000,-54.8000,1620956435,42.80,61,0,5.75,42.80
3,ponta do sol,-17.1000,32.6667,1620956632,60.37,55,20,17.27,66.20
4,anadyr,177.4833,64.7500,1620956633,35.26,87,75,6.71,35.60
...,...,...,...,...,...,...,...,...,...
563,shu,73.7614,43.5983,1620956839,58.71,44,55,1.97,58.71
564,mehamn,27.8492,71.0357,1620956840,33.84,66,97,11.97,33.84
565,bandiagara,-3.6104,14.3501,1620956840,88.81,11,71,4.21,88.81
566,mecca,39.8261,21.4267,1620956841,82.22,30,0,5.55,82.22
567,maniwaki,-75.9660,46.3834,1620956841,50.00,66,98,2.30,50.00

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# Check data types of imported weather data
weather_data_df.dtypes

City                    object
Longitude              float64
Latitude               float64
Date                     int64
Temperature (F)        float64
Humidity (%)             int64
Cloudiness (%)           int64
Wind Speed (mph)       float64
Max Temperature (F)    float64
dtype: object

In [9]:
# Add latitude and longitude to locations list, add humidity to humidity, and change data types to float for 
# latitude, longitude, and humidity

locations = weather_data_df[["Latitude", "Longitude"]].astype(float)
humidity = weather_data_df["Humidity (%)"].astype(float)

In [10]:
# Confirm data types of locations are both floats
locations.dtypes

Latitude     float64
Longitude    float64
dtype: object

In [11]:
# Confirm data type of humidity is float
humidity.dtypes

dtype('float64')

In [12]:
# Create gmaps figure
fig1 = gmaps.figure()

# Create humidity heatmap layer
humidity_layer = gmaps.heatmap_layer(locations, weights = humidity)

# Add humidity heatmap layer to fig1
fig1.add_layer(humidity_layer)

# Display fig1
fig1

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [24]:
# Filter cities so that Max Temperature (F) is between 70F and 80F and Wind Speed (mph) is less than 5
vacation_destinations = weather_data_df[(weather_data_df["Max Temperature (F)"] < 80) & 
                                        (weather_data_df["Max Temperature (F)"] > 70) &
                                        (weather_data_df["Wind Speed (mph)"] < 5)]

# Drop rows with null values
vacation_destinations = vacation_destinations.dropna()

# Reset index
vacation_destinations.reset_index(drop=True, inplace=True)

In [25]:
vacation_destinations

,City,Longitude,Latitude,Date,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Max Temperature (F)
0,tefe,-64.7114,-3.3542,1620956640,72.68,97,26,1.61,72.68
1,sao filipe,-24.4956,14.8961,1620956652,75.18,72,5,4.88,75.18
2,naze,129.4833,28.3667,1620956656,73.40,100,75,4.61,73.40
3,puerto ayora,-90.3518,-0.7393,1620956468,75.99,93,64,4.00,75.99
4,manacapuru,-60.6206,-3.2997,1620956658,77.00,94,40,2.30,77.00
5,manaquiri,-60.3500,-3.3167,1620956672,77.00,94,40,2.30,77.00
6,olga,135.2892,43.7444,1620956697,70.74,29,0,4.05,70.74
7,natal,-35.2094,-5.7950,1620956697,75.20,94,75,3.44,75.20
8,raga,25.6780,8.4596,1620956710,72.36,89,100,3.36,72.36
9,eirunepe,-69.8736,-6.6603,1620956711,72.77,98,99,2.24,72.77
10,bandundu,17.3667,-3.3167,1620956718,74.73,76,100,1.99,74.73
11,mangai,19.5333,-4.0500,1620956718,72.73,71,66,0.65,72.73
12,touros,-35.4608,-5.1989,1620956719,75.20,94,75,2.30,75.20
13,cao bang,106.2500,22.6667,1620956721,79.12,87,100,4.68,79.12
14,manaus,-60.0250,-3.1019,1620956431,77.00,94,40,2.30,77.00
15,kollam,76.6000,8.8833,1620956727,77.00,100,90,4.61,77.00
16,sibolga,98.7792,1.7427,1620956729,78.33,86,100,1.10,78.33
17,sungaipenuh,101.3833,-2.0833,1620956743,74.61,79,83,1.23,74.61
18,port macquarie,152.9167,-31.4333,1620956568,70.03,55,0,4.00,71.01
19,wanxian,108.3897,30.8039,1620956772,77.97,77,100,4.56,77.97
20,maragogi,-35.2225,-9.0122,1620956776,76.14,88,100,4.36,76.14
21,tura,90.2201,25.5198,1620956778,74.01,85,19,4.23,74.01
22,carutapera,-46.0200,-1.1950,1620956778,75.81,93,100,4.50,75.81
23,itaituba,-55.9836,-4.2761,1620956779,76.60,88,99,1.10,76.60
24,gamba,10.0000,-2.6500,1620956781,77.23,88,100,1.05,77.23
25,iwaki,140.8833,37.0500,1620956786,73.80,68,34,1.01,75.99
26,mayumba,10.6554,-3.4320,1620956794,78.26,86,100,0.85,78.26
27,yenagoa,6.2642,4.9247,1620956796,76.10,89,89,1.68,76.10
28,inirida,-67.9239,3.8653,1620956799,73.35,96,99,1.36,73.35
29,inongo,18.2667,-1.9500,1620956810,73.06,84,100,2.30,73.06
30,nara,135.8049,34.6851,1620956810,76.08,73,40,4.61,77.00
31,padang,100.3543,-0.9492,1620956812,78.80,94,40,4.61,78.80
32,vernon,-119.2691,50.2581,1620956821,69.30,34,27,2.30,72.00
33,faya,42.4509,18.3851,1620956826,70.70,37,40,4.61,71.60
34,meulaboh,96.1285,4.1363,1620956584,79.79,81,88,2.91,79.79
35,keffi,7.8736,8.8486,1620956834,74.10,81,89,2.86,74.10
36,berekum,-2.5840,7.4534,1620956838,71.60,95,96,4.14,71.60

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure